const KEY='ciel.web.v1', tabs={heute:'Heute',termine:'Termine',einkauf:'Einkauf',aufgaben:'Aufgaben',notizen:'Notizen',hilfe:'Mehr'};
let tab='heute', data={appointments:[],shopping:[],tasks:[],notes:[]},storageOK=true;
const $=s=>document.querySelector(s),escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
try{const raw=localStorage.getItem(KEY);if(raw){const parsed=JSON.parse(raw);if(!Object.keys(data).every(k=>Array.isArray(parsed[k])))throw Error();data=parsed;}}catch{storageOK=false;$('#status').textContent='Daten konnten nicht geladen werden. Bitte Website neu öffnen; es wird nichts überschrieben.';}
function save(next){if(!storageOK)return false;try{localStorage.setItem(KEY,JSON.stringify(next));data=next;return true;}catch{$('#status').textContent='Speichern fehlgeschlagen. Bitte freien Speicher prüfen.';return false;}}
function go(id){tab=id;render();}
function itemRows(key,preview=false){let rows=preview?data[key].filter(x=>!x.done).slice(0,3):data[key];return rows.length?rows.map(x=>`<div class="row">${key!=='notes'?`<button class="check" data-toggle="${key}" data-id="${escape(x.id)}" aria-label="${x.done?'Als offen':'Als erledigt'} markieren">${x.done?'✓':'○'}</button>`:''}<div class="grow ${x.done?'done':''}">${escape(x.text)}${x.person?`<div class="tag">${escape(x.person)}</div>`:''}</div>${preview?'':`<button class="delete" data-delete="${key}" data-id="${escape(x.id)}">Löschen</button>`}</div>`).join(''):'<p>Noch keine Einträge. Mach deinen Kopf ein bisschen freier.</p>';}
function appointmentRows(rows){return rows.map(x=>`<div class="row"><div class="grow"><strong>${escape(x.title)}</strong><div class="muted">${new Date(x.date).toLocaleString('de-DE',{dateStyle:'medium',timeStyle:'short'})}</div></div><button data-export="${escape(x.id)}">Kalender</button><button class="delete" data-delete="appointments" data-id="${escape(x.id)}">Löschen</button></div>`).join('')||'<p>Keine Termine eingetragen.</p>';}
function render(){ $('nav').innerHTML=Object.entries(tabs).map(([k,v])=>`<button data-tab="${k}" class="${tab===k?'active':''}" aria-current="${tab===k?'page':'false'}">${v}</button>`).join('');let html='';
if(tab==='heute'){const today=new Date().toDateString();html=`<h2>Hallo. Was steht heute an?</h2><p>${new Date().toLocaleDateString('de-DE',{weekday:'long',day:'numeric',month:'long'})}</p><div class="card"><h3>Deine Termine heute</h3>${appointmentRows(data.appointments.filter(x=>new Date(x.date).toDateString()===today))}<div class="actions"><button data-tab="termine">Termin hinzufügen</button></div></div><div class="card"><h3>Offene Aufgaben · ${data.tasks.filter(x=>!x.done).length}</h3>${itemRows('tasks',true)}<div class="actions"><button data-tab="aufgaben">Alle Aufgaben</button></div></div><div class="card"><h3>Einkauf · ${data.shopping.filter(x=>!x.done).length} offen</h3>${itemRows('shopping',true)}<div class="actions"><button data-tab="einkauf">Zur Einkaufsliste</button></div></div>`;}
else if(tab==='termine'){html=`<h2>Platz für eure Pläne.</h2><p>Kinderarzt, Elternabend oder Geburtstag — alles an einem Ort.</p><form id="appointment"><label>Terminname<input name="title" placeholder="Mia · Kinderarzt" required maxlength="250"></label><div class="split"><label>Datum<input type="date" name="date" required></label><label>Uhrzeit<input type="time" name="time" required value="14:00"></label></div><label>Erinnerungen für den Kalenderexport<select name="mode"><option value="daily">7 Tage täglich + zum Termin</option><option value="day">1 Tag vorher + zum Termin</option><option value="only">Nur zum Termin</option></select></label><button class="primary">Termin speichern</button></form><div class="card"><h3>Gespeicherte Termine</h3>${appointmentRows(data.appointments)}</div><p>Diese Web-App sendet keine automatischen Mitteilungen. „Kalender“ lädt eine .ics-Datei zum Import. Ob Erinnerungen übernommen werden, hängt von deiner Kalender-App ab; bitte dort prüfen.</p>`;}
else if(tab==='hilfe'){html=`<h2>Dein Ciel.</h2><div class="card"><h3>Ein eigenes Symbol</h3><p>Öffne diesen Link in Safari. Tippe auf Teilen → Zum Home-Bildschirm → Hinzufügen.</p><button id="help">Hinweise anzeigen</button></div><div class="card"><h3>Deine Daten sichern</h3><p>Die Daten bleiben auf diesem Gerät. Eine Sicherungsdatei kannst du aufheben oder auf einem anderen Handy importieren. Ein Import ersetzt die dort gespeicherten Ciel-Daten.</p><div class="actions"><button id="backup">Sicherung herunterladen</button><button id="restore">Sicherung importieren</button></div><input type="file" id="file" accept="application/json,.json" hidden></div><div class="card"><h3>Ideen für den Alltag</h3><p>Aufgaben: Schulzettel unterschreiben, Sporttasche packen.<br>Notizen: Ausflug-Packliste, Geschenkideen, Wochenessen.<br>Termine: Namen voranstellen, etwa „Ben · Elternabend“.</p></div>`;}
else{const key={einkauf:'shopping',aufgaben:'tasks',notizen:'notes'}[tab];html=`<h2>${tabs[tab]}</h2><p>${{einkauf:'Was fehlt zu Hause? Mengen direkt dazuschreiben.',aufgaben:'Kleine Dinge festhalten und Schritt für Schritt abhaken.',notizen:'Packlisten, Ideen und Gedanken für später.'}[tab]}</p><form id="list" data-key="${key}"><label>${tab==='notizen'?'Deine Notiz':'Neuer Eintrag'}<${tab==='notizen'?'textarea':'input'} name="text" required maxlength="5000" placeholder="${{einkauf:'2 Liter Milch',aufgaben:'Sporttasche packen',notizen:'Für den Ausflug brauchen wir …'}[tab]}">${tab==='notizen'?'</textarea>':''}</label>${tab==='aufgaben'?'<label>Für wen? (optional)<input name="person" maxlength="100" placeholder="Mia"></label>':''}<button class="primary">Hinzufügen</button></form><div class="card">${itemRows(key)}</div>${tab==='einkauf'?'<button id="share">Offene Einkäufe teilen</button>':''}<p>${tab==='aufgaben'?'Aufgaben haben noch keine eigenen zeitgesteuerten Erinnerungen. Für feste Zeiten nutze einen Termin.':'Alles bleibt auf diesem Gerät gespeichert.'}</p>`;}
$('#view').innerHTML=html;}
function download(name,content,type){const url=URL.createObjectURL(new Blob([content],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);}
function icsEscape(text){return text.replace(/\\/g,'\\\\').replace(/\r?\n/g,'\\n').replace(/,/g,'\\,').replace(/;/g,'\\;');}
function stamp(date){return date.toISOString().replace(/[-:]/g,'').replace(/\.\d{3}/,'');}
function exportCalendar(x){const date=new Date(x.date);const days=x.mode==='daily'?[7,6,5,4,3,2,1,0]:x.mode==='day'?[1,0]:[0];const lines=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//Ciel//Familienalltag//DE','BEGIN:VEVENT','UID:'+x.id+'@ciel.local','DTSTAMP:'+stamp(new Date()),'DTSTART:'+stamp(date),'DTEND:'+stamp(new Date(+date+3600000)),'SUMMARY:'+icsEscape(x.title),...days.flatMap(d=>['BEGIN:VALARM','ACTION:DISPLAY','DESCRIPTION:'+icsEscape(x.title),'TRIGGER:'+(d?'-P'+d+'D':'PT0S'),'END:VALARM']),'END:VEVENT','END:VCALENDAR'];download('ciel-termin.ics',lines.join('\r\n')+'\r\n','text/calendar;charset=utf-8');}
document.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.tab)go(b.dataset.tab);if(b.dataset.toggle){const k=b.dataset.toggle;const next={...data,[k]:data[k].map(x=>x.id===b.dataset.id?{...x,done:!x.done}:x)};if(save(next))render();}if(b.dataset.delete&&confirm('Diesen Eintrag löschen?')){const k=b.dataset.delete;if(save({...data,[k]:data[k].filter(x=>x.id!==b.dataset.id)}))render();}if(b.dataset.export)exportCalendar(data.appointments.find(x=>x.id===b.dataset.export));if(b.id==='help')$('#info').showModal();if(b.id==='backup')download('ciel-sicherung.json',JSON.stringify(data,null,2),'application/json');if(b.id==='restore')$('#file').click();if(b.id==='share'){const text='Unsere Einkaufsliste\n'+data.shopping.filter(x=>!x.done).map(x=>'• '+x.text).join('\n');try{if(navigator.share)await navigator.share({title:'Einkaufsliste',text});else{download('einkaufsliste.txt',text,'text/plain');}}catch(err){if(err.name!=='AbortError')$('#status').textContent='Teilen konnte nicht geöffnet werden.';}}});
document.addEventListener('submit',e=>{e.preventDefault();const form=e.target,f=new FormData(form);let next;const id=crypto.randomUUID();if(form.id==='appointment'){const date=new Date(f.get('date')+'T'+f.get('time'));if(!Number.isFinite(+date)||date<=new Date()){$('#status').textContent='Bitte einen Termin in der Zukunft wählen.';return;}if(!f.get('title').trim())return;next={...data,appointments:[...data.appointments,{id,title:f.get('title').trim(),date:date.toISOString(),mode:f.get('mode')}].sort((a,b)=>new Date(a.date)-new Date(b.date))};}else{const k=form.dataset.key,text=f.get('text').trim();if(!text)return;next={...data,[k]:[...data[k],{id,text,person:(f.get('person')||'').trim(),done:false}]};}if(save(next)){$('#status').textContent='Gespeichert.';render();}});
document.addEventListener('change',async e=>{if(e.target.id!=='file'||!e.target.files[0])return;try{const file=e.target.files[0];if(file.size>2000000)throw Error();const parsed=JSON.parse(await file.text());for(const k of Object.keys(data)){if(!Array.isArray(parsed[k])||parsed[k].length>10000)throw Error();for(const x of parsed[k]){if(typeof x.id!=='string')throw Error();if(k==='appointments'){if(typeof x.title!=='string'||!Number.isFinite(+new Date(x.date))||!['daily','day','only'].includes(x.mode))throw Error();}else if(typeof x.text!=='string'||typeof x.done!=='boolean'||typeof x.person!=='string')throw Error();}}if(confirm('Die Sicherung ersetzt alle aktuellen Ciel-Daten auf diesem Gerät. Fortfahren?')&&save(parsed)){$('#status').textContent='Sicherung importiert.';render();}}catch{$('#status').textContent='Diese Sicherung ist ungültig oder zu groß.';}});
render();document.addEventListener('visibilitychange',()=>{if(!document.hidden&&tab==='heute')render();});
