let voiceDraft='', voiceMessage='Tippe auf das Mikrofon und sprich einen Auftrag.', recognition=null,voiceTimer=null,voiceStarting=false;
function parseVoice(input, now=new Date()) {
 const text=input.trim().replace(/^(?:hey\s+)?(?:ciel|jarvis)[\s,:]*/i,'').replace(/[.!?]+$/,'').trim();
 let m=text.match(/^(?:setze|setz|schreibe|schreib|füge)\s+(.+?)\s+(?:auf|zur|zu|in)\s+(?:die|der|meine|meiner)\s+einkaufsliste(?:\s+hinzu)?$/i);
 if(m)return {type:'add',key:'shopping',text:m[1]};
 m=text.match(/^kaufe\s+(.+)$/i);if(m)return {type:'add',key:'shopping',text:m[1]};
 m=text.match(/^(?:notiere|notier|merke dir|notiz)\s*[:,-]?\s+(.+)$/i);if(m)return {type:'add',key:'notes',text:m[1]};
 m=text.match(/^(?:aufgabe|neue aufgabe|erinnere mich daran)\s*[:,-]?\s+(.+)$/i);if(m)return {type:'add',key:'tasks',text:m[1]};
 m=text.match(/^(?:zeige|zeig|öffne)\s+(?:(?:mir|meine|die|meinen)\s+)*(termine|einkaufsliste|aufgaben|notizen|heute)$/i);
 if(m)return {type:'navigate',tab:{termine:'termine',einkaufsliste:'einkauf',aufgaben:'aufgaben',notizen:'notizen',heute:'heute'}[m[1].toLowerCase()]};
 m=text.match(/^(?:(?:erstelle|erstelle mir|lege|lege mir)\s+(?:einen\s+)?termin\s*(?:für\s+)?|termin\s*[:,-]?\s*)(?:am\s+)?(heute|morgen|übermorgen|\d{1,2}\.\s*\d{1,2}\.(?:\s*\d{4})?)\s+um\s+(\d{1,2})(?:\s*[:.]\s*(\d{2}))?\s*(?:uhr)?\s*[:,-]?\s+(.+)$/i);
 if(m){let date=new Date(now),h=+m[2],min=+(m[3]||0);if(h>23||min>59)return {type:'error',message:'Diese Uhrzeit ist ungültig.'};const word=m[1].toLowerCase();if(['heute','morgen','übermorgen'].includes(word)){date.setDate(date.getDate()+({heute:0,morgen:1,übermorgen:2}[word]));}else{const parts=word.replace(/\s/g,'').split('.');const d=+parts[0],mo=+parts[1],y=parts[2]?+parts[2]:now.getFullYear();date=new Date(y,mo-1,d);if(date.getFullYear()!==y||date.getMonth()!==mo-1||date.getDate()!==d)return {type:'error',message:'Dieses Datum ist ungültig.'};}date.setHours(h,min,0,0);if(date<=now)return {type:'error',message:'Der Termin liegt in der Vergangenheit. Bitte Datum und Jahr nennen.'};return {type:'appointment',title:m[4].trim(),date};}
 return {type:'error',message:'Noch nicht verstanden. Nutze eines der Beispiele unten oder ändere den erkannten Text.'};
}
function renderVoice(){const supported=!!(window.SpeechRecognition||window.webkitSpeechRecognition);$('#voice-panel').innerHTML=`<h2>Sag Ciel, was ansteht.</h2><p>Ein Auftrag pro Aufnahme. Das Mikrofon hört nur, solange du die Aufnahme gestartet hast.</p><div class="card"><button id="mic" class="primary">${recognition||voiceStarting?'■ Aufnahme beenden':'🎙 Auftrag sprechen'}</button><p id="voice-status" role="status">${escape(voiceMessage)}</p><label>Erkannter Text / eigener Befehl<textarea id="voice-text" placeholder="Setze Milch auf die Einkaufsliste">${escape(voiceDraft)}</textarea></label><div class="actions"><button id="voice-run">Befehl ausführen</button><button id="voice-read">Antwort vorlesen</button></div></div>${supported?'':'<p>Dieses Browserfenster bietet keine Spracherkennung. Tippe ins Textfeld und nutze das Mikrofon der iPhone-Tastatur.</p>'}<div class="card"><h3>Das versteht Ciel</h3><p>„Setze Milch auf die Einkaufsliste“<br>„Aufgabe: Sporttasche packen“<br>„Notiere: Geschenkidee für Oma“<br>„Zeige meine Termine“<br>„Termin morgen um 15 Uhr Kinderarzt“<br>„Termin am 25.10.2026 um 14:30 Elternabend“</p></div><p>Erkannte Listenbefehle werden direkt ausgeführt. Termine werden zuerst im Formular angezeigt und erst nach deiner Bestätigung gespeichert. Die Spracherkennung verwendet den Dienst deines Browsers und kann eine Internetverbindung benötigen. Bei Problemen öffne Ciel direkt in Safari und nutze alternativ die Tastatur-Diktierfunktion.</p>`;}
function voiceStatus(message){voiceMessage=message;if($('#voice-status'))$('#voice-status').textContent=message;$('#status').textContent=message;}
function runVoice(input){const parsed=parseVoice(input);if(parsed.type==='error'){voiceStatus(parsed.message);return;}
 if(parsed.type==='navigate'){voiceMessage='Hier sind deine '+tabs[parsed.tab]+'.';go(parsed.tab);$('#status').textContent=voiceMessage;return;}
 if(parsed.type==='appointment'){go('termine');const form=$('#appointment');const d=parsed.date;form.elements.title.value=parsed.title;form.elements.date.value=[d.getFullYear(),String(d.getMonth()+1).padStart(2,'0'),String(d.getDate()).padStart(2,'0')].join('-');form.elements.time.value=String(d.getHours()).padStart(2,'0')+':'+String(d.getMinutes()).padStart(2,'0');voiceStatus('Bitte Termin kontrollieren und mit „Termin speichern“ bestätigen.');return;}
 if(save({...data,[parsed.key]:[...data[parsed.key],{id:crypto.randomUUID(),text:parsed.text,person:'',done:false}]})){voiceStatus('Gespeichert: '+parsed.text);if(tab==='sprache')renderVoice();}
}
function stopVoice(){clearTimeout(voiceTimer);voiceTimer=null;if(recognition){try{recognition.abort();}catch{}recognition=null;}voiceStarting=false;}
function startVoice(){if(recognition||voiceStarting){stopVoice();voiceStatus('Aufnahme beendet.');renderVoice();return;}const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){voiceStatus('Bitte das Mikrofon der iPhone-Tastatur im Textfeld nutzen.');return;}window.speechSynthesis?.cancel();voiceStarting=true;let handled=false;const r=new SR();recognition=r;r.lang='de-DE';r.continuous=false;r.interimResults=true;
 r.onstart=()=>{if(recognition!==r)return;voiceStarting=false;voiceStatus('Ich höre zu …');renderVoice();};
 r.onresult=e=>{if(recognition!==r||handled)return;let final='';let interim='';for(let i=0;i<e.results.length;i++){const chunk=e.results[i][0].transcript;if(e.results[i].isFinal)final+=chunk;else interim+=chunk;}voiceDraft=(final||interim).trim();if($('#voice-text'))$('#voice-text').value=voiceDraft;if(final.trim()){handled=true;stopVoice();runVoice(final.trim());if(tab==='sprache')renderVoice();}};
 r.onerror=e=>{if(recognition!==r)return;stopVoice();voiceStatus(({ 'not-allowed':'Mikrofon oder Spracherkennung nicht erlaubt. Prüfe Safari-Berechtigungen; alternativ die Tastatur-Diktierfunktion nutzen.','service-not-allowed':'Spracherkennung nicht verfügbar. Prüfe Siri/Diktierfunktion in den iPhone-Einstellungen oder nutze Tastatur-Diktieren.','no-speech':'Keine Sprache erkannt. Bitte erneut versuchen.','network':'Sprachdienst nicht erreichbar. Prüfe deine Internetverbindung.','audio-capture':'Mikrofon nicht verfügbar.'})[e.error]||'Spracherkennung fehlgeschlagen. Bitte Tastatur-Diktieren verwenden.');if(tab==='sprache')renderVoice();};
 r.onend=()=>{if(recognition!==r)return;stopVoice();if(!handled)voiceStatus('Aufnahme beendet. Prüfe den Text und tippe gegebenenfalls auf „Befehl ausführen“.');if(tab==='sprache')renderVoice();};
 voiceTimer=setTimeout(()=>{if(recognition===r){stopVoice();voiceStatus('Aufnahme beendet. Falls nichts erkannt wurde, bitte die Tastatur-Diktierfunktion verwenden.');if(tab==='sprache')renderVoice();}},20000);
 try{r.start();voiceStatus('Mikrofon wird gestartet …');renderVoice();}catch{stopVoice();voiceStatus('Mikrofon konnte nicht gestartet werden. Bitte Tastatur-Diktieren nutzen.');renderVoice();}}
document.addEventListener('input',e=>{if(e.target.id==='voice-text')voiceDraft=e.target.value;});
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.tab&&b.dataset.tab!=='sprache')stopVoice();if(b.id==='mic')startVoice();if(b.id==='voice-run'){stopVoice();runVoice(voiceDraft);}if(b.id==='voice-read'){stopVoice();if(window.speechSynthesis){const u=new SpeechSynthesisUtterance(voiceMessage);u.lang='de-DE';window.speechSynthesis.cancel();window.speechSynthesis.speak(u);}}});
document.addEventListener('visibilitychange',()=>{if(document.hidden)stopVoice();});
